### ISSUE TITLE
Changing / deleting uploaded files?

### ISSUE THREAD

**Issue by martin-braun** [somenonymous/OshiUpload#13]
Meta data of uploaded files could be stored in the localStorage and used to change or delete uploaded files. I.e. change the expiration time or invalidate a download link.

**Comment by somenonymous** [comment]
Every uploaded file has its separate management interface on the private link. It permits changing expiration time and deleting uploads. 

Storing meta data of uploaded files client-side will permit tracking and break privacy. There is also no point to do so because there is already a secure way of managing uploads via individual private links.

**Comment by martin-braun** [comment]
Good to know, I wasn't aware of this! Thanks.
