### ISSUE TITLE
Upload failed 

### ISSUE THREAD

**Issue by zell180** [somenonymous/OshiUpload#24]
Hi, from 2-3 days upload failed both website and http. Why?

**Comment by somenonymous** [comment]
Some issues happen to our server from time to time due to performance degradation at increased traffic and resource usage, but when I am available I just readjust database performance options or make some decision to disable some functionality of the Oshi engine so it can live again. I am still studying those cases which sometimes seem to be intentional abuse of our IOPS and other resources since the Oshi engine is not very limiting at all, but I will for sure deploy some update soon that would give a node operator to enforce some temporary policies to prevent abuse of resource usage.


This particular issue was related to our database being misconfigured which got a fix now.


I will also host an email server to get better communication between oshi.at users and its operators.
