### ISSUE TITLE
Hoster Issue?

### ISSUE THREAD

**Issue by kkarhan** [somenonymous/OshiUpload#25]
Apparently it seems as if https://oshi.at is geoblocking Germany as attempts to connect to caused it to go 404 but not on the Tor Browser...

Is this intentional?
![Bildschirmfoto vom 2023-05-17 20-45-42](https://github.com/somenonymous/OshiUpload/assets/30401796/0984048b-2012-4767-9b10-e8a4c56c57cf)

**Comment by elandorr** [comment]
Using a random sniffed open proxy (apparently some hotel forgot security)

ASN	3320
ASN Name	Deutsche Telekom AG
Country Code	DE

I can access oshi.at just fine. oshi doesn't blacklist DE.

German bans are weird, though, some German ISPs practice preemptive obedience and censor all kinds of stuff even before gov orders come in.

**Comment by kkarhan** [comment]
Yeah, basically all ISPs in Germany do shit like [Contentmafia-Based DNS Censorship](https://de.wikipedia.org/wiki/Clearingstelle_Urheberrecht_im_Internet).

But [I don't use my ISPs DNS](https://github.com/greyhat-academy/lists.d/blob/main/dns.servers.list.tsv) and if it oshi.at was blacklisted [DTAG would've blocked it as well due to being CUII member](https://de.wikipedia.org/wiki/Clearingstelle_Urheberrecht_im_Internet#Mitglieder).

In fact, [I do purge DNS providers from my repo if they censor the records or otherwise alter the responses](https://github.com/greyhat-academy/lists.d/commit/ddf967a84dafb6c5b8f3191b79aa42db7ffab866)...

Since I've taken further analysis it seems as if [the IPv4 version of the website is being served form a rogue ISP that has been blocked on my end](https://github.com/greyhat-academy/lists.d/blob/f118c37badb0b7b0d2fb1ba7260e9b9483a2115a/drop.ipv4.block.list.tsv#L176)...
![Bildschirmfoto vom 2023-05-20 04-43-21](https://github.com/somenonymous/OshiUpload/assets/30401796/189501ba-eb2d-4648-aeb3-fe985427ec9d)

If @somenonymous finds time to migrate webhosters I'd recommend to change that...

**Comment by elandorr** [comment]
I think we should **stop pinging him directly** or indirectly via non-relevant issues here. Github discussions aren't enabled here, but [here's one](https://github.com/elandorr/test/discussions/2) on a fresh repo. I'm quite busy, but I'm passionate about these topics so feel free to chat there.

Your ISP could block directly, too. Just automate it like I used to do for Google etc. DNS blacklists are just 'entry-level' as Europe is incompetent and it's good enough to keep 90% of people out.

Regarding that host, **it's not a 'rogue ISP'**. It's one of the few decent ISPs left that knows what free speech means. Read the comment above the line you linked:

`##	AS208046	Maximilian Kutzner trading as HostSlick / hostslick.com	Rogue ISP	Providing Hosting Services for Hategrooming Forum [KiwiFarms]`

Wherever you copied those lists from is some system parrot blindly following the Zeitgeist. No such thing as 'hatespeech' - or you have to censor everything. It doesn't capture the subtleties of indirect insults, either. I can insult your very core without ever using anything deemed offensive, but that's the coward's way. I feel personally attacked every time I'm forced to read system sheep, now that's _real_ 'hatespeech'.
Someone should make common-sense-list that filters these obedient parrots. But no need.
**Genuine humans can click 'close'.** Easy enough.

Thanks, though, now I found another hoster for our list of ISPs that respect a free internet.

I know a hoster on there personally, good stuff. Some of these people really fight for freedom, which is insanely difficult in Europe.

**Close this issue here as there is no issue.** Obviously you cannot host oshi on a system shill. It'd be taken down, raided in 5 mins. No system shill allows legit anonymity or privacy.

**Comment by somenonymous** [comment]
We never ever geoblock anything, but thanks a lot for your concern. I'd vouch for keeping such topics within the https://github.com/somenonymous/OshiUpload/issues/9 scope for now, since it fits better there and have nothing to do with the code itself.
