### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by thuiop** [somenonymous/OshiUpload#26]
Hello,

I have been trying to use this tool today (with the oshi.at instance) but have been encountering a lot of issues ; in particular accessing the files does not seem to work reliably, and I often get a 502 error (it only works sometimes, and even then I have to wait more than 10 seconds to get a < 100 Ko file). Is this a temporary issue ?

**Comment by somenonymous** [comment]
Some issues happen to our server from time to time due to performance degradation at increased traffic and resource usage, but when I am available I just readjust database performance options or make some decision to disable some functionality of the Oshi engine so it can live again. I am still studying those cases which sometimes seem to be intentional abuse of our IOPS and other resources since the Oshi engine is not very limiting at all, but I will for sure deploy some update soon that would give a node operator to enforce some temporary policies to prevent abuse of resource usage.


This particular issue was related to our database being misconfigured which got a fix now.


I will also host an email server to get better communication between oshi.at users and its operators.

**Comment by thuiop** [comment]
Ok, thanks for the info ! In the end I setup my own instance for my private use ; thanks for the great package.
